
NOMS_IA = ["General Chang", "Sybok", "Bajorans extrémistes", "Vedeks radicaux", "Section 31", "Gorkon le Klingon"]

A_TOI_DE_JOUER = [
    "Le capitaine Solaris vous dit : « Cible verrouillée. À vous de tirer. »",
    "Votre officier scientifique signale une ouverture : profitez-en.",
    "Le commandant Arcturus compte sur votre précision.",
    "La passerelle se tait… c’est votre moment.",
    "Les satellites alliés confirment la zone d’impact. Feu !",
    "Votre navigateur murmure : « Je ne louperais pas celle-là… »",
    "Les étoiles s’alignent. Attaquez maintenant.",
    "Votre bras droit tactique : « Faites-leur regretter de nous avoir défiés. »",
    "Les systèmes d'armement vibrent d'impatience.",
    "Un léger sourire apparaît sur le visage de l’amiral : « Montrez-leur. »",
    "Toute la flotte retient son souffle, capitaine.",
    "Votre instinct vous le dit : c’est le bon tir.",
    "Les capteurs long-portée dévoilent une faiblesse critique.",
    "L’ingénieur chef confirme : « Les canons sont chauds. »",
    "Une porte d’opportunité vient de s’ouvrir. Visez juste.",
    "Le commandant Vortex vous lance : « Faites parler vos canons. »",
    "La stratégie galactique dépend de ce tir. À vous de jouer.",
    "Les drones éclaireurs valident la trajectoire optimale.",
    "Votre équipage attend votre geste… Ne les faites pas languir.",
    "Une vibration dans le vaisseau : l’ennemi hésite. Profitez-en.",
    "La galaxie entière semble observer l’issue de votre tir.",
    "L’amiral Zenith croit en votre précision légendaire.",
    "Les capteurs thermiques indiquent : cible vulnérable.",
    "Votre officier de communication : « Le champ est libre. Tirez ! »",
    "Les ennemis ne s’attendent pas à votre coup maintenant.",
    "Les calculs sont faits. À vous d’appuyer sur la détente.",
    "Picard vous dit d'attaquer tant qu'il est encore temps.",
    "Spock pense que la paix vaut mieux… mais pour l’instant, défendez-vous.",
    "Le commandant Shepard vous ordonne de prendre l’initiative.",
    "L’amiral Nova demande un tir précis sur la position ennemie.",
    "Le capitaine Orion vous fait signe : c’est le moment d’ouvrir le feu.",
    "L’IA du vaisseau calcule une fenêtre d’attaque : agissez vite.",
    "Votre officier tactique attend votre ordre, capitaine.",
    "Les senseurs détectent une faiblesse adverse : c’est le moment d’attaquer.",
    "Le commandant Vega vous rappelle : la meilleure défense, c’est l’attaque.",
    "Votre équipage vous regarde, prêt à suivre votre prochain tir.",
    "Les scanners confirment une cible vulnérable. À vous de jouer.",
    "Le stratège Helios murmure que la victoire est à portée de main.",
    "Le copilote Kaelis vous dit : « Montrez-leur ce qu’on vaut ! »",
    "Un silence tendu envahit la passerelle… Tout le monde attend votre tir.",
    "Les boucliers ennemis semblent instables. C’est le moment idéal.",
    "Votre radar affiche une ouverture rare. Profitez-en, capitaine.",
    "Les moteurs de tir sont chargés. Il ne manque plus que votre ordre.",
    "La flotte alliée compte sur vous. Choisissez votre cible.",
    "L’état-major vous envoie : « Feu à volonté ! »",
    "L’IA tactique recommande une frappe immédiate.",
    "Le capitaine Nova sourit : « Faites trembler les étoiles. »",
    "Votre ennemi hésite… Prenez l’avantage !",
    "Une opportunité parfaite d’attaque vient d’apparaître.",
    "Le commandant Stellar vous encourage : « Concentrez votre tir. »",
    "Les étoiles elles-mêmes semblent retenir leur souffle… À vous de jouer.",
]


A_TOI_DE_RATER = [
    "Un souffle passe dans la passerelle… Tir manqué.",
    "Votre officier tactique grimace : « Rien touché… »",
    "Les senseurs confirment : impact nul.",
    "Le capitaine Solaris soupire : « Ce n’était pas loin. »",
    "Votre navigateur annonce : « Déviation légère… dommage. »",
    "Le tir se perd dans le vide intersidéral.",
    "L’IA du vaisseau calcule : « Probabilité de succès précédente… surestimée. »",
    "Les ennemis esquivent agilement votre attaque.",
    "Votre bras droit murmure : « On fera mieux au prochain tir, capitaine. »",
    "La trajectoire était parfaite… mais la cible ne l’était pas.",
    "L’ingénieur chef annonce : « Aucun dégât détecté chez l’ennemi. »",
    "Les scanners affichent : zéro impact.",
    "Le commandant Arcturus reste calme : « Ajustez et recommencez. »",
    "Votre officier de communication tente d’être encourageant : « On les aura la prochaine. »",
    "Le commandant Vortex souffle : « Ils ont eu de la chance… cette fois. »",
    "Votre tir fend l’air mais ne touche rien.",
    "Les boucliers ennemis n’ont même pas tremblé.",
    "Votre instinct vous le dit : ce tir n’était pas le bon.",
    "Les drones éclaireurs confirment : aucun dommage.",
    "Votre copilote Kaelis murmure : « On loupe tous un tir parfois… »",
    "Le commandant Shepard vous glisse : « Concentrez-vous, capitaine. »",
    "Spock élève un sourcil : « Une erreur… logique. »",
    "Picard dirait sûrement : « On apprend de ses échecs. Continuez. »",
    "L’amiral Nova soupire : « L’ennemi a eu chaud… mais rien de plus. »",
    "Votre radar reste muet : aucune signature d’impact.",
    "Les moteurs de tir frémissent… en attente d’une meilleure occasion.",
    "Votre stratège Helios note : « L’ennemi est plus mobile qu’il n’y paraît. »",
    "Le silence qui suit en dit long… c’est un raté.",
    "Votre équipage détourne légèrement le regard… mais garde confiance.",
    "Les étoiles semblent vous dire : « On ne gagne pas tous les coups. »",
    "Votre officier scientifique note : « Échec enregistré. »",
    "L’IA tactique suggère : « Correction de trajectoire recommandée. »",
    "Une onde se propage dans l’eau… sans toucher de métal ennemi.",
    "Le commandant Vega déclare : « Ils ne t’échapperont pas longtemps. »",
    "Votre radar affiche : « Aucun contact destructif. »",
    "Les systèmes d’armement ronronnent, prêts à réessayer.",
    "Votre navigateur : « Leur mouvement était imprévisible. »",
    "L’amiral Zenith reste confiant : « Ce n’est qu’un tir. »",
    ]